### ISSUE TITLE
Please upgrade to 1.5.1

### ISSUE THREAD

**Issue by Guite** [mrohnstock/leaflet#2]
It would be nice if you could update Leaflet to the latest release: https://github.com/Leaflet/Leaflet/releases/tag/v1.5.1

**Comment by mrohnstock** [comment]
Done :). Feel free to create a PR for a new version of Leaflet next time.

**Comment by Guite** [comment]
Thanks a lot!

**Comment by Guite** [comment]
@mrohnstock can you please trigger the update on packagist.org? The latest version there is still 1.3.1.

**Comment by mrohnstock** [comment]
hm for me it's already 1.5.1, maybe it got updated right now?

**Comment by Guite** [comment]
Right, now it is updated. Weird. Maybe because you logged in?

**Comment by mrohnstock** [comment]
that could be possible... strange... what ever ;) have a nice weekend

**Comment by Guite** [comment]
Thanks. I wish you the same.
